### ISSUE TITLE
CD doesn't show for Convoke the Spirit. [Bug]: 

### ISSUE THREAD

**Issue by Jorhall** [ascott18/TellMeWhen#1995] opened 2022-11-07 22:16 UTC
### WoW Version

Retail

### TellMeWhen Version

10.0.1

### Describe the bug

When setting up the icon there are two channelled spells in the suggestion list. I have tried them both. 
I'm a resto druid and I have it as a talent.

### Export Strings

```text
^1^T^SShowTimer^B ^SType^Scooldown ^SShowTimerText^B ^SName^SConvoke~`the~`Spirits ^SClockGCD^B ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SCAv ^t^t^t^SStates^T ^N2^T ^SAlpha^N1 ^t^t^SEnabled^B ^t^N100100^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment] 2022-11-07 22:25
Duplicate of #1978. You need to track it by ID because Blizzard broke their API for some covenant abilities.

**Closed by ascott18** 2022-11-07 22:25 UTC
Labels: S: wontfix
