### ISSUE TITLE
TMW Snippet: Scale bug

### ISSUE THREAD

**Issue by SiderealDay** [ascott18/TellMeWhen#2057] opened 2023-01-08 09:24 UTC
### WoW Version

Retail

### TellMeWhen Version

10.0.7

### Describe the bug

I deleted everything in TMW, until it warned me there was nothing to show.
I reloadedui. Now, there are no groups, no profiles and no snippets on this character.

I created a new profile and group.
But every time I tried to resize the 4-cell row by dragging the triangle. the row kept shrinking by itself into a very small size.

So again, I deleted everything (no group, profiles, or snippets) and reloadedui.
But the resize issue persisted. I also managed to get the error below.
Not sure what the cause could be if there are literally no snippets. I just cannot resize anymore.

### Export Strings

```text
9x [string "TMW Snippet: Scale"]:18: attempt to index global 'TellMeWhen_Group1' (a nil value)
[string "TMW Snippet: Scale"]:18: in function <[string "TMW Snippet: Scale"]:8>
Locals:
self = Frame {
 0 = <userdata>
 TimeSinceLastUpdate = 0
}
elapsed = 16.485001
myhight = 1080
myscale1 = 0.426667
myscale2 = 0.177778
(*temporary) = nil
(*temporary) = nil
(*temporary) = "1920x1080"
(*temporary) = "gxWindowedResolution"
(*temporary) = "1920x1080"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'TellMeWhen_Group1' (a nil value)"
```

**Comment by ascott18** [comment] 2023-01-08 18:14
Duplicate of #2056

**Closed by ascott18** 2023-01-08 18:14 UTC
