### ISSUE TITLE
[Bug] Spell cooldown not beeing able to track the cd of Eternity Surge

### ISSUE THREAD

**Issue by Betaskill** [ascott18/TellMeWhen#2083] opened 2023-05-03 16:46 UTC
### WoW Version

Retail

### TellMeWhen Version

10.1.0 - German Client

### Describe the bug

Hello there, 

TMW is currently not able to to track the Spell Eternity Surge with Spell Cooldown. It is currently only possible with Reactive Ability.

Thanks for the hard work.

 

### Export Strings

```text
^1^T^SType^Scooldown ^SName^S359073 ^SEnabled^B ^t^N101000^S~`~| ^Sicon^^
```

**Comment by Betaskill** [comment] 2023-05-03 16:56
I have taken another look, this is only happening with the Talent "Font of Magic", like in this post described:

https://github.com/ascott18/TellMeWhen/issues/2081#issue-1693239903

now just for Eternity Surge.

**Comment by ascott18** [comment] 2023-05-05 03:33
Duplicate of #2081

**Closed by ascott18** 2023-05-05 03:33 UTC
