### ISSUE TITLE
[Fire Breath]

### ISSUE THREAD

**Issue by WOWTMWWOW** [ascott18/TellMeWhen#2103] opened 2023-07-28 17:47 UTC
### WoW Version

Retail

### TellMeWhen Version

10.1.5

### Describe the bug

Emprowered spell stage dont working if stage >3. good work only for 0, 1, 2 and 3

### Export Strings

```text
^1^T^SType^Scast ^SConditions^T ^N1^T ^SType^SEMPOWEREDSTAGE ^SOperator^S>= ^SAndOr^SOR ^SName^S382266 ^SLevel^N3 ^t^Sn^N1 ^t^SGUID^STMW:icon:1amviIV3HPe8 ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^S ^N2^S ^t^t^t^SEnabled^B ^t^N101500^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment] 2023-07-29 05:45
Duplicate of #2021

**Closed by ascott18** 2023-07-29 05:45 UTC
