### ISSUE TITLE
Meta icon not updated if conditional icon has talent loadout as the condition

### ISSUE THREAD

**Issue by arbybee** [ascott18/TellMeWhen#2076] opened 2023-02-26 06:22 UTC
### WoW Version

Retail

### TellMeWhen Version

3.4.1

### Describe the bug

With a meta icon displaying conditional icons that use talent loadout as the condition, changing the loadout does not cause the new icon to be displayed, although it seems to take effect.  It is necessary to /reload ui to get the proper icon displayed.

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment] 2023-02-26 22:54
TellMeWhen has never had a version 3.4.1. Had it existed, it would have been in early 2011.

Also, duplicate of https://github.com/ascott18/TellMeWhen/issues/2038

**Closed by ascott18** 2023-02-26 22:54 UTC
