### ISSUE TITLE
Invalid setalpha params cause lua errors

### ISSUE THREAD

**Issue by Debuggernaut** [ascott18/TellMeWhen#2168] opened 2024-07-11 12:28 UTC
### WoW Version

Retail

### TellMeWhen Version

2

### Describe the bug

I fixed the issue and sent a PR already, which seems to have been automatically closed without merging:

Fix - Lua error, invalid params to SetAlpha #2079 https://github.com/ascott18/TellMeWhen/pull/2079

### Export Strings

```text
1
```

**Comment by ascott18** [comment] 2024-07-12 03:51
Duplicate of https://github.com/ascott18/TellMeWhen/issues/2085.

I closed your PR because it looks like it was an abandoned work in progress, still being full of all kinds of commented out debugging code.

**Comment by ascott18** [comment] 2024-07-12 03:55
Actually as I look more closely, what you changed in your PR isn't quite the same spot was #2085. In that case...

Please do not ignore the issue template that is provided when you create a new issue. The questions and sections within it provide me with essential information to be able to diagnose and resolve your issue. If you won't include this information, I probably won't help you.

**Closed** 2024-07-12 05:22 UTC
