### ISSUE TITLE
[Bug]: DogTags

### ISSUE THREAD

**Issue by Shamorisse** [ascott18/TellMeWhen#1971] opened 2022-10-26 13:44 UTC
### WoW Version

Retail

### TellMeWhen Version

v10.0.0

### Describe the bug

Unable to search dogtags in an icon's "text displays". It brings up a list of spell ids instead

Typing /dt causes a lua error

```
42x ...terface/AddOns/TellMeWhen/Lib/LibDogTag-3.0-20220904190516/Help.lua:33: attempt to call method 'SetMinResize' (a nil value)
[string "@Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0-20220904190516/Help.lua"]:33: in function `OpenHelp'
[string "@Interface/AddOns/TellMeWhen/Components/Core/Common/DogTags/config.lua"]:245: in function `OnSuggest'
[string "@Interface/AddOns/TellMeWhen/Components/Core/Suggester/Suggester.lua"]:378: in function `NameOnCursor'
[string "@Interface/AddOns/TellMeWhen/Components/Core/Suggester/Suggester.lua"]:494: in function <...s/TellMeWhen/Components/Core/Suggester/Suggester.lua:475>

Locals:
self = <table> {
 unparse = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Parser.lua:1233
 select2 = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Helpers.lua:155
 callbackToFunction = <table> {
 }
 hasEvent = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Events.lua:185
 callbackToExtraArg = <table> {
 }
 __colors = <table> {
 }
 Tags = <table> {
 }
 CleanCode = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Parser.lua:1595
 codeToFunction = <table> {
 }
 newDict = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Helpers.lua:35
 clearCodes = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Helpers.lua:516
 TimerHandlers = <table> {
 }
 UnregisterCustomClassColors = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/LibDogTag-3.0.lua:617
 ADDON_LOADED = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/LibDogTag-3.0.lua:519
 PLAYER_LOGIN = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/LibDogTag-3.0.lua:609
 AddCallback = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Events.lua:219
 RemoveCompilationStep = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Compiler.lua:2259
 _clearCodes = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Helpers.lua:441
 kwargsToKwargTypesWithTableCache = <table> {
 }
 RemoveEventHandler = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Events.lua:761
 newSet = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Helpers.lua:51
 __mytonumber = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Compiler.lua:292
 OpenHelp = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Help.lua:25
 EventHandlers = <table> {
 }
 RemoveCallback = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Events.lua:268
 parse = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Parser.lua:1043
 frame = Frame {
 }
 fixNamespaceList = <table> {
 }
 fsToFrame = <table> {
 }
 eventUsed = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Events.lua:91
 compilationSteps = <table> {
 }
 AddTag = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/LibDogTag-3.0.lua:129
 AddCompilationStep = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Compiler.lua:2232
 kwargsToKwargTypes = <table> {
 }
 usedEvents = <table> {
 }
 __lastMouseover = EditBox {
 }
 ClearNamespace = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/LibDogTag-3.0.lua:586
 UpdateFontString = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/LibDogTag-3.0.lua:330
 AddEventHandler = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Events.lua:730
 UnitToLocale = <table> {
 }
 standardize = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Parser.lua:1063
 RemoveAllCompilationSteps = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Compiler.lua:2286
 IsLegitimateUnit = <table> {
 }
 IsNormalUnit = <table> {
 }
 getTagData = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Compiler.lua:247
 ColorizeCode = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Parser.lua:1670
 memoizeTable = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Helpers.lua:315
 RemoveFontString = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/LibDogTag-3.0.lua:452
 joinSet = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Helpers.lua:162
 RemoveTimerHandler = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Events.lua:850
 Evaluate = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Compiler.lua:2198
 sortStringList = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Helpers.lua:138
 AddTimerHandler = <function> defined @Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Events.lua:814
 FireEvent = <function> defined @Interface/AddO
```

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment] 2022-10-26 16:49
Duplicate of #1967. As a workaround for now, you can install LibDogTag-3.0 as a standalone addon.

**Closed by ascott18** 2022-10-26 16:49 UTC
