### ISSUE TITLE
LUA error when logging into an alt for the first time in a while - table index is nil

### ISSUE THREAD

**Issue by raysmith59** [ascott18/TellMeWhen#2216] opened 2024-09-04 21:31 UTC
### WoW Version

Retail

### TellMeWhen Version

11.0.5

### Describe the bug

Logged in, got this error.  When I went into /tmw to get the version it happened again.

1x TellMeWhen: TellMeWhen/Components/Core/Common/Actions.lua:43: table index is nil
[string "@TellMeWhen/TellMeWhen.lua"]:2872: in function <TellMeWhen/TellMeWhen.lua:2829>

Locals:
self = TMW {
 CovenantIcons = <table> {
 }
 modules = <table> {
 }
 DS = <table> {
 }
 db = <table> {
 }
 ALLOW_LOCKDOWN_CONFIG = true
 operators = <table> {
 }
 isNumber = <table> {
 }
 COMMON = <table> {
 }
 TEXT = <table> {
 }
 EquivFullIDLookup = <table> {
 }
 InitializedDatabase = true
 name = "TellMeWhen"
 Defaults = <table> {
 }
 C = <table> {
 }
 BackupDate = "05:28:35 PM"
 SNIPPETS = <table> {
 }
 L = <table> {
 }
 OrderedTypes = <table> {
 }
 justifyVPoints = <table> {
 }
 Views = <table> {
 }
 CHANGELOG = "## v11.0.5
* Spell Cooldown and Reactive Ability icons are vastly more efficient if the tracked ability is on your action bars (macros excluded).
  * This is done by utilizing new WoW 11.0 APIs that are specific to abilities present on action bars.
* Fix: #2197 upstream issue in LibSpellRange-1.0 with range checking in classic/cata.
* Fix: #2201 Don't treat inactive hero talent trees as learned talents

## v11.0.4
* Fix: #2186 Activation overlays in Retail
* The cooldown charge sweep is now skinned with Masque.

## v11.0.3
* Fix activation overlays in Classic
* Fix the Tracking ACtive condition (again)

## v11.0.2
* Support Masque round spell activation overlays. 
  * Must be enabled in Masque -> General Settings -> Advanced -> Spell Alert Style (pick anything other than "None").
* Fix: #2178 Spell dragging to icons broken (again) in WoW 11.0
* Fix: #2179 Tracking Active condition broken in WoW 11.0
* Fix: #2182 Unlearned choice node talents missing from suggestion list
* Fix: #2181 Totem trac defaultModuleState = true
 CHANGELOG_LASTVER = "10.0.0"
 HELP = <table> {
 }
 UPD_INTV = 0.051000
 Locked = true
 NAMES = <table> {
 }
 GUIDToOwner = <table> {
 }
 justifyPoints = <table> {
 }
 CompareFuncs = <table> {
 }
 GCD = 0
 EventList = <table> {
 }
 EVENTS = <table> {
 }
 EquivOriginalLookup = <table> {
 }
 CONST = <table> {
 }
 indentLib = <table> {
 }
 GroupsToUpdate = <table> {
 }
 GCDSpell = 53
 Classes = <table> {
 }
 isRetail = true
 Group_Defaults = <table> {
 }
 SpellTexturesMetaIndex = <table> {
 }
 performedEvent = "TMW_UPGRADE_PERFORMED"
 UNITS = <table> {
 }
 isWrath = false
 profile = <table> {
 }
 DOGTAG = <table> {
 }
 IconStateArbitrator = <table> {
 }
 time = 33964.484000
 IconEventUpdateEngine = Frame {
 }
 isCata = false
 baseName = "TellMeWhen"
 TIMERS = <table> {
 }
 Backupdb = <table> {
 }
 SUG = <table> {
 }
 strlowerCache = <table> {
 }
 DD = <table> {
 }
 DROPDOWNMENU = <table> {
 }
 CNDT = <table> {
 }
 enabledState = true
 points = <table> {
 }
 IE = TellMeWhen_IconEditor {
 }
 CI = <table> {
 }
 spellTextureCache = <table> {
 }
 isClassic = false
 Initialized = true
 EquivFirstIDLookup = <table> {
 }
 EquivFullNameLookup = <table> {
 }
 DEFAULT_ICON_SETTINGS = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 BE = <table> {
 }
 IconsToUpdate = <table> {
 }
 PreviousGUIDToOwner = <table> {
 }
 COUNTERS = <table> {
 }
 ValidityCheckQueue = <table> {
 }
 orderedModules = <table> {
 }
 IconDragger = <table> {
 }
 Icon_Defaults = <table> {
 }
 OrderedViews = <table> {
 }
 Types = <table> {
 }
 HaveUpgradedOnce = true
 global = <table> {
 }
 callbackregistry = <table> {
 }
}
success = false
err = "TellMeWhen/Components/Core/Common/Actions.lua:43: table index is nil"
time = 33964.484000
TMW = TMW {
 CovenantIcons = <table> {
 }
 modules = <table> {
 }
 DS = <table> {
 }
 db = <table> {
 }
 ALLOW_LOCKDOWN_CONFIG = true
 operators = <table> {
 }
 isNumber = <table> {
 }
 COMMON = <table> {
 }
 TEXT = <table> {
 }
 EquivFullIDLookup = <table> {
 }
 InitializedDatabase = true
 name = "TellMeWhen"
 Defaults = <table> {
 }
 C = <table> {
 }
 BackupDate = "05:28:35 PM"
 SNIPPETS = <table> {
 }
 L = <table> {
 }
 OrderedTypes = <table> {
 }
 justifyVPoints = <table> {
 }
 Views = <table> {
 }
 CHANGELOG = "## v11.0.5
* Spell Cooldown and Reactive Ability icons are vastly more efficient if the tracked ability is on your action bars (macros excluded).
  * This is done by utilizing new WoW 11.0 APIs that are specific to abilities present on action bars.
* Fix: #2197 upstream issue in Li

### Export Strings

```text
N/A (far as I can tell)
```

**Comment by ascott18** [comment] 2024-09-04 23:41
Duplicate of #2205, #2208, #2213

**Closed by ascott18** 2024-09-04 23:41 UTC
