### ISSUE TITLE
tmw not showing, and not interactable

### ISSUE THREAD

**Issue by abicodue** [ascott18/TellMeWhen#2249] opened 2024-11-02 08:04 UTC
### WoW Version

Classic or SoD

### TellMeWhen Version

11.0.11

### Describe the bug

the thing is, tmw is working fine for my already existing characters. However, for newly created characters, only global groups work and profile groups don't work. profile groues' icons are invisible and not clickable either. even if you import from other characters, it's the same, imported profile groups exist there, but they are not on my screen(invisible and not clickable). I checked spec/class conditons and etceteras, every conditons are same as already existing characters' settings.
r/classicwow - only Resize button shows and you can drag it, but the icons are invisible and not interactable/clickable.

![텔미웬](https://github.com/user-attachments/assets/a613d69a-f538-4e22-92fd-5b59c5fbbd6c)

only Resize button shows and you can drag it, but the icons are invisible and not interactable/clickable.
PLEASE HELP!

### Export Strings

```text
^1^T^SGUID^STMW:group:1d9S=GRjQLmn ^SScale^N1.2 ^SColumns^N1 ^t^N11001101^S~`~| ^Sgroup^N1 ^^
```

**Comment by avarath2022** [comment] 2024-11-02 13:52
Same issue I have.

**Comment by ascott18** [comment] 2024-11-02 16:36
Duplicate of #2248

**Closed by ascott18** 2024-11-02 16:36 UTC
