### ISSUE TITLE
Couple LUA errors after Cata Firelands patch

### ISSUE THREAD

**Issue by Memon82** [ascott18/TellMeWhen#2243] opened 2024-10-30 10:36 UTC
### WoW Version

Cata Classic

### TellMeWhen Version

11.0.10

### Describe the bug

After the patch TMW appears to be spamming LUA errors non-stop due to "attempt to call upvalue 'GetSpecialization' (a nil value)" as well as another error I've attached.

[TMW_Interface_Error.txt](https://github.com/user-attachments/files/17570642/TMW_Interface_Error.txt)
[TMW_GetSpec_Error1.txt](https://github.com/user-attachments/files/17570643/TMW_GetSpec_Error1.txt)
[TMW_GetSpec_Error2.txt](https://github.com/user-attachments/files/17570645/TMW_GetSpec_Error2.txt)

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment] 2024-10-30 23:27
Duplicate of #2239, fixed in 11.0.11

**Closed by ascott18** 2024-10-30 23:27 UTC
