### ISSUE TITLE
classic SOD - find minerals stopped working after the last update

### ISSUE THREAD

**Issue by dihhrox** [ascott18/TellMeWhen#2139] opened 2023-12-30 12:46 UTC
### WoW Version

Classic/Classic SoM

### TellMeWhen Version

tellmewhen v10.2.1

### Describe the bug

the condition of checking the activated track stopped detecting find minerals, even with it selected and marked in the box as "false" to be displayed only when the track is not active, it continues to display the icon, as if it had not detected the track active

along with when I click on the box to choose which track I will select, the suggestion box next to it does not report any options, as if there were no items in the list of possible tracks for it to suggest

### Export Strings

```text
^1^T^SShowTimer^B ^SType^Scooldown ^SName^SFind~`Minerals ^SConditions^T ^N1^T ^SType^STRACKING ^SOperator^S<= ^SLevel^N1 ^SName^SFind~`Minerals ^t^N2^T ^SType^SINSTANCE2 ^SChecked^B ^SBitFlags^N6 ^t^Sn^N2 ^t^SClockGCD^B ^SOnlyMine^B ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SN9 ^N2^S ^t^t^t^SStates^T ^N1^T ^SAlpha^N0.5 ^t^t^SFakeHidden^B ^SGUID^STMW:icon:1bRUtJAwqnya ^t^N102101^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment] 2023-12-30 18:52
Duplicate of #2137

**Closed by ascott18** 2023-12-30 18:52 UTC
