### ISSUE TITLE
lua error, GetItemCooldown function does not exist anymore

### ISSUE THREAD

**Issue by ssateneth** [ascott18/TellMeWhen#2062] opened 2023-01-18 00:51 UTC
### WoW Version

Wrath Classic

### TellMeWhen Version

10.0.8 r5 (g28fcbec)

### Describe the bug

lua error, because the function GetItemCooldown no longer exists and is actually in C_Container now

Message: TellMeWhen: ...ce/AddOns/TellMeWhen/Components/Core/Common/Item.lua:227: attempt to call upvalue 'GetItemCooldown' (a nil value)
Time: Tue Jan 17 18:39:09 2023
Count: 1
Stack: TellMeWhen: ...ce/AddOns/TellMeWhen/Components/Core/Common/Item.lua:227: attempt to call upvalue 'GetItemCooldown' (a nil value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "@Interface/AddOns/TellMeWhen/Components/Core/Utils.lua"]:445: in function `Error'
[string "@Interface/AddOns/TellMeWhen/TellMeWhen.lua"]:2811: in function <Interface/AddOns/TellMeWhen/TellMeWhen.lua:2768>

Locals: <none>

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment] 2023-01-18 00:55
Duplicate of #2046

**Closed by ascott18** 2023-01-18 00:55 UTC
