### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by GnomeTW** [ascott18/TellMeWhen#1877] opened 2021-03-20 16:21 UTC
**What version of TellMeWhen are you using? **
V 9.0.5

**What steps will reproduce the problem?**
1.
2.
3.

**What do you expect to happen? What happens instead?**

**Screenshots and Export Strings**

1x invalid key to 'next'
[string "=[C]"]: in function `(for generator)'
[string "@TellMeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0-20210228122115.lua"]:49: in function <...MeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua:46>
[string "@TellMeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0-20210228122115.lua"]:56: in function <...MeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua:55>

Locals:
Skipped (In Encounter)

**Comment by ascott18** [comment] 2021-03-20 16:38
Duplicate of  #1876

**Closed by ascott18** 2021-03-20 16:38 UTC
