### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wowmacro** [ascott18/TellMeWhen#1982] opened 2022-10-29 07:32 UTC
### WoW Version

Retail

### TellMeWhen Version

10.0.0

### Describe the bug

get LUA errors when I login in WoW
1x Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.xml:258 Unrecognized XML attribute: urgency
1x Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.xml:259 Unrecognized XML attribute: urgency
1x Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.xml:260 Unrecognized XML attribute: urgency
1x Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.xml:261 Unrecognized XML attribute: urgency
1x Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.xml:262 Unrecognized XML attribute: urgency
1x Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.xml:600 Unrecognized XML attribute: urgency
1x Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.xml:607 Unrecognized XML attribute: urgency
1x Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.xml:765 Unrecognized XML attribute: change
1x Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.xml:766 Unrecognized XML attribute: change
1x Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.xml:836 Unrecognized XML attribute: change

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment] 2022-10-29 17:55
Duplicate of #1974

**Closed by ascott18** 2022-10-29 17:55 UTC
