### ISSUE TITLE
How to get the number of Monk's new talent 'Aspect of Harmony'?

### ISSUE THREAD

**Issue by Hurunshu** [ascott18/TellMeWhen#2209] opened 2024-09-01 09:39 UTC
![image](https://github.com/user-attachments/assets/86f9a08e-30d3-46f6-a3ec-d1871c93028a)
It can not be obtained by [Value] [ValueMax] or First Non-zero variable or Only variable #1 2 3 with [Stacks]

**Comment by ascott18** [comment] 2024-09-02 02:45
Duplicate of #2190

**Closed by ascott18** 2024-09-02 02:45 UTC
