### ISSUE TITLE
Classic SoD - Errors after patch today

### ISSUE THREAD

**Issue by Painstormx** [ascott18/TellMeWhen#2150] opened 2024-02-07 18:27 UTC
### WoW Version

Classic/Classic SoM

### TellMeWhen Version

10.2.2

### Describe the bug

A new patch hit SoD today.
Getting errors on login:
Date: 2024-02-07 19:25:00
ID: 1
Error occured in: Global
Count: 1
Message: TellMeWhen: ...e/AddOns/TellMeWhen/Components/Core/Common/Auras.lua line 342:
   attempt to call upvalue 'UnitAuraSlots' (a nil value)
Debug:
   [string "@Interface/AddOns/TellMeWhen/TellMeWhen.lua"]:2820:
      Interface/AddOns/TellMeWhen/TellMeWhen.lua:2777
Locals:
self = TMW {
 0 = <userdata>
 OnGCD = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:376
 Vararg = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:1036
 SlashCommand = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:3023
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface/AddOns/DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:147
 GroupsToUpdate = <table> {
 }
 GetBaseUpgrades = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:1514
 GCDSpell = 53
 InNLengthTable = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:1060
 InIconSettings = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:926
 GetSpells = <function> defined 			local cachemeta = { __mode = 'kv' }
			local cache = setmetatable({}, cachemeta)
			local nilKey = {}
			local func = ...
			return function(arg1,arg2,arg3, ...)
	local next, prev, key = cache
	
 key = arg1 == nil and nilKey or arg1
 prev = next; next = prev[key]
 if not next then next = setmetatable({}, cachemeta) prev[key] = next end
 key = arg2 == nil and nilKey or arg2
 prev = next; next = prev[key]
 if not next then next = setmetatable({}, cachemeta) prev[key] = next end
 key = arg3 == nil and nilKey or arg3
 prev = next; next = prev[key]	if next ~= nil then return next end
	local ret = func(arg1,arg2,arg3, ...)
		prev[key] = ret
		return ret;
	end, cache
	:5
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 TryGetNPCName = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:1610
 Classes = <table> {
 }
 DS = <table> {
 }
 TT_Parse = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:1245
 IsEnabled = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 HSVToRGB = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:716
 isRetail = false
 UnregisterMessage = <function> defined @Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 Update = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:2865
 AnimateHeightChange = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:1332
 toSeconds = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:476
 isClassic = true
 Group_Defaults = <table> {
 }
 GetParser = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:1573
 GetDataOwner = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:1329
 SetEnabledState = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 CopyWithMetatable = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:924
 ValidateType = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:551
 SpellTexturesMetaIndex = <table> {
 }
 InGroups = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:1002
 tDeleteItem = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:827
 RegisterLuaImportDetector = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:1646
 tContains = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:808
 Fire = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:823
 InGroupSettings = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:964
 Initialized = true
 EquivFirstIDLookup = <table> {
 }
 tRemoveDuplicates = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:845
 EquivFullNameLookup = <table> {
 }
 StringToCachedRGBATable = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:364
 GameTooltip_SetSpellByIDWithClassIcon = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Spells/ClassSpellCache.lua:167
 UpdateGlobals = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:2563
 DEFAULT_ICON_SETTINGS = <table> {
 }
 db = <table> {
 }

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment] 2024-02-07 20:04
Duplicate of #2148

**Closed** 2024-02-07 20:26 UTC
