### ISSUE TITLE
Allow Config in Combat is blocking Keybindings

### ISSUE THREAD

**Issue by Betaskill** [ascott18/TellMeWhen#2128] opened 2023-11-30 23:05 UTC
### WoW Version

Retail

### TellMeWhen Version

10.2.0

### Describe the bug

Hello there,

I have started recently to play again as you can see :) and the option in the general-menu "Allow config in combat" is causing the keybindungs to block completely if you are reloading, while you are still stuck in combat. After you are out of the combat the keybindungs are usable again. 

Not sure if this is intended. 
![grafik](https://github.com/ascott18/TellMeWhen/assets/55817239/d22d4ea1-492c-4846-8b8b-7370c0633596)

Thanks again

### Export Strings

```text
No String
```

**Comment by ascott18** [comment] 2023-12-01 05:39
duplicate of #2122

**Closed by ascott18** 2023-12-01 05:39 UTC
