### ISSUE TITLE
Bug: Spell cast present condition not trackable with the last empowered stage

### ISSUE THREAD

**Issue by Betaskill** [ascott18/TellMeWhen#2032] opened 2022-11-27 19:05 UTC
### WoW Version

Retail

### TellMeWhen Version

10.0.4 retail(not alpha)

### Describe the bug

Its me again. 

I am trying to track if my empowerded spells, Eternity Surge and / or Fire Breath are present with a simple condition icon. 

There is one weird problem. If I am adding the "unit speed" condition always, the last stage of the spells are not beeing tracked as present. 

If I remove the "unit speed", the "Tracks spell casts and channels." condition is tracking the last stage as it should be. 

Thanks again for taking a look at it

Edit at 20:08 o´clock: have uploaded the correct string
Edit 2: On second thought it is contradictory to use a  "unit speed" condition for a cast where you have to stay still, but perhaps that behavior is maybe part of a bigger problem

### Export Strings

```text
^1^T^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SSPEED ^t^N2^T ^SType^SCASTING ^SLevel^N1 ^SName^S359073 ^t^Sn^N2 ^t^SName^SEwigkeitswoge ^SManaCheck^B ^SEnabled^B ^SCooldownCheck^B ^SCustomTex^S359073 ^SStates^T ^N3^T ^SAlpha^N0 ^t^N4^T ^SAlpha^N0 ^t^t^SRangeCheck^B ^t^N100300^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment] 2022-11-27 19:45
This is a manifestation of https://github.com/ascott18/TellMeWhen/issues/2021#issuecomment-1328008241 and https://github.com/Stanzilla/WoWUIBugs/issues/355. I currently have no plans to implement a workaround because its absolutely on Blizzard to fix this one. Closing as a duplicate of #2021.

**Closed by ascott18** 2022-11-27 19:45 UTC

**Comment by ascott18** [comment] 2022-11-27 19:47
The reason it breaks when you add a Unit Speed condition is that this condition forces the entire set of conditions to use interval-based updates. With just the cast condition, there's no update triggered until the cast ends so it sort of functions as an accidental workaround.
