### ISSUE TITLE
Issue with librangecheck?

### ISSUE THREAD

**Issue by pvpratings** [ascott18/TellMeWhen#2034] opened 2022-11-28 05:02 UTC
### WoW Version

Retail

### TellMeWhen Version

10.0.4

### Describe the bug

Message: [string "Condition_ICON_LIBRANGECHECK_ITEMCD_DEBUFFD..."]:5: attempt to index field '?' (a nil value)
Time: Sun Nov 27 23:46:23 2022
Count: 4472
Stack: [string "Condition_ICON_LIBRANGECHECK_ITEMCD_DEBUFFD..."]:5: attempt to index field '?' (a nil value)
[string "Condition_ICON_LIBRANGECHECK_ITEMCD_DEBUFFDUR_ITEMEQUIPPED_BUFFDUR_BUFFDUR_BUFFDUR_BUFFDUR"]:5: in function `CheckFunction'
[string "@Interface/AddOns/TellMeWhen/Components/Core/Conditions/ConditionObject.lua"]:266: in function `Check'
[string "@Interface/AddOns/TellMeWhen/Components/Core/Icon.lua"]:756: in function <Interface/AddOns/TellMeWhen/Components/Core/Icon.lua:727>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/TellMeWhen/TellMeWhen.lua"]:2626: in function <Interface/AddOns/TellMeWhen/TellMeWhen.lua:2588>

Locals: <none>

### Export Strings

```text
I don't know.  I believe it's for a certain icon, the error only pops up when I'm targeting someone.
Thanks!
```

**Comment by ascott18** [comment] 2022-11-28 05:08
Duplicate of #2026, #2028, #2033

**Closed by ascott18** 2022-11-28 05:08 UTC
