### ISSUE TITLE
Some lua errors from today

### ISSUE THREAD

**Issue by CaRuJa1** [ascott18/TellMeWhen#2028] opened 2022-11-27 13:18 UTC
### WoW Version

Retail

### TellMeWhen Version

v10.0.4

### Describe the bug

Hey there, I'm getting a lot of errors thrown into bugsack essentially on start up.  I just walk around the covenant hall and get a pile of errors.  Sorry that isn't much context, but I'll share them below and hopefully they are helpful:

------

77x [string "Condition_ITEMINBAGS"]:3: attempt to index field '?' (a nil value)
[string "Condition_ITEMINBAGS"]:3: in function `CheckFunction'
[string "@TellMeWhen/Components/Core/Conditions/ConditionObject.lua"]:266: in function <...eWhen/Components/Core/Conditions/ConditionObject.lua:260>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@TellMeWhen/Components/Core/Conditions/ConditionObject.lua"]:235: in function `RegisterForUpdating'
[string "@TellMeWhen/Components/Core/Conditions/ConditionObject.lua"]:319: in function `DeclareExternalUpdater'
[string "@TellMeWhen/Components/Core/Icon.lua"]:1040: in function <TellMeWhen/Components/Core/Icon.lua:926>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@TellMeWhen/Components/Core/Group.lua"]:497: in function <TellMeWhen/Components/Core/Group.lua:425>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@TellMeWhen/TellMeWhen.lua"]:2714: in function `UpdateNormally'
[string "@TellMeWhen/TellMeWhen.lua"]:2863: in function `Update'
[string "@TellMeWhen/TellMeWhen.lua"]:2871: in function `?'
[string "@Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

------

20771x [string "Condition_ITEMCD_COMBAT_ICON_ICON"]:3: attempt to index field '?' (a nil value)
[string "Condition_ITEMCD_COMBAT_ICON_ICON"]:3: in function `CheckFunction'
[string "@TellMeWhen/Components/Core/Conditions/ConditionObject.lua"]:266: in function `Check'
[string "@TellMeWhen/Components/Core/Conditions/UpdateEngine.lua"]:151: in function <...llMeWhen/Components/Core/Conditions/UpdateEngine.lua:146>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[4]"]:9: in function <[string "safecall Dispatcher[4]"]:5>
[string "=(tail call)"]: ?
[string "@TellMeWhen/TellMeWhen.lua"]:828: in function `Fire'
[string "@TellMeWhen/TellMeWhen.lua"]:2609: in function <TellMeWhen/TellMeWhen.lua:2588>

------

### Export Strings

```text
N/A
```

**Comment by solitha** [comment] 2022-11-27 15:44
I came here for much the same reason. Looks like an alpha update fixes it though, look for 10.0.4-3.

**Comment by ascott18** [comment] 2022-11-27 18:23
Duplicate of #2026

**Closed by ascott18** 2022-11-27 18:23 UTC
