### ISSUE TITLE
[Bug]: Cast bars have no text

### ISSUE THREAD

**Issue by Bokogit** [ascott18/TellMeWhen#1975] opened 2022-10-26 20:03 UTC
### WoW Version

Retail

### TellMeWhen Version

10.0.0

### Describe the bug

Cast bars for target and focus are not showing any text. Spell icons for some spells are showing though.

### Export Strings

```text
^1^T^SUnit^Starget ^SType^Scast ^SInterruptible^B ^SEnabled^B ^t^N100000^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment] 2022-10-27 03:52
Unable to reproduce. 
![image](https://user-images.githubusercontent.com/5017521/198187256-d93eae2d-56a7-4857-ad5c-04013af28b21.png)

**Comment by Bokogit** [comment] 2022-10-27 16:48
Sorry. I should have tried again in another zone. It only seems to be happing in battlegrounds.

**Comment by Alwies** [comment] 2022-10-28 23:32
Can replicate with vertical bars, seems related to #1977

**Comment by ascott18** [comment] 2022-10-29 02:25
Closing in favor of #1977. If that is not your issue then please file a new issue and include screenshots and an export string of your entire profile.

**Closed by ascott18** 2022-10-29 02:25 UTC
