### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by MoritzBradtke** [ascott18/TellMeWhen#1893] opened 2021-05-02 18:27 UTC
**What version of TellMeWhen are you using? **

v9.0.6 classic
**What steps will reproduce the problem?**
1.cast healing wave in wow classic on shaman with path of healing 3/3
2. cast healing wave on any target beside yourself while tracking "path of healing" buff on "target"
3. if u cast the path of healing buff on any target beside yourself, tellmewhen will no longer track the buff if the target already has the max amount of 3 stacks

**What do you expect to happen? What happens instead?**

the bar for the buff should uptade its duration timer, instead it will just drop to zero duration over time as it wont renew the timer with 3 stacks, resulting in an empty bar with 0 stacks and 0 duration after a while, building the buff up again starting with 1 stack will work if the 3 stack buff has worn already until the same problem occurs again if u try to keep the buff up with 3 stacks maximum

**Screenshots and Export Strings**

**Additional Info**

for some reason i dont have this problem on my own character if i target myself, it doesnt work on random npcs or other players tough, the buff will be tracked on everyone but on everyone beside my own character it stops working as intentended when the buff hits its maximum 3 stacks !

**Comment by ascott18** [comment] 2021-05-04 01:33
Duplicate of https://github.com/ascott18/TellMeWhen/issues/1792

**Closed by ascott18** 2021-05-04 01:33 UTC
