### ISSUE TITLE
LUA Error when targeting a mob with debuff icons tracked

### ISSUE THREAD

**Issue by kirbuslee** [ascott18/TellMeWhen#2149] opened 2024-02-06 19:40 UTC
### WoW Version

Classic/Classic SoM

### TellMeWhen Version

10.2.2

### Describe the bug

I have a TMW bar set up to track specific debuffs on my target, and when I target something, the bar does not become visible and the following LUA error pops up:

Message: ...e/AddOns/TellMeWhen/Components/Core/Common/Auras.lua:342: attempt to call upvalue 'UnitAuraSlots' (a nil value)
Time: Tue Feb  6 14:38:38 2024
Count: 1
Stack: ...e/AddOns/TellMeWhen/Components/Core/Common/Auras.lua:342: attempt to call upvalue 'UnitAuraSlots' (a nil value)
[string "@Interface/AddOns/TellMeWhen/Components/Core/Common/Auras.lua"]:342: in function <...e/AddOns/TellMeWhen/Components/Core/Common/Auras.lua:330>
[string "@Interface/AddOns/TellMeWhen/Components/Core/Conditions/Categories/BuffsDebuffs.lua"]:119: in function `AuraDurPacked'
[string "ConditionEvents_DEBUFFDUR_DEBUFFDUR"]:8: in function `UpdateFunction'
[string "@Interface/AddOns/TellMeWhen/Components/Core/Conditions/UpdateEngine.lua"]:131: in function <...llMeWhen/Components/Core/Conditions/UpdateEngine.lua:124>
[string "=[C]"]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

Locals: unit = "target"
unitData = <table> {
 lookup = <table> {
 }
 instances = <table> {
 }
}
instances = <table> {
}
lookup = <table> {
}
(*temporary) = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Common/Auras.lua:298
(*temporary) = "target"
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = "target"
(*temporary) = "HELPFUL"
(*temporary) = "attempt to call upvalue 'UnitAuraSlots' (a nil value)"
data = <table> {
 target = <table> {
 }
 player = <table> {
 }
}
UpdateAuras = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Common/Auras.lua:298
UnitAuraSlots = nil

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment] 2024-02-07 02:05
Duplicate of #2148

**Closed by ascott18** 2024-02-07 02:05 UTC
