### ISSUE TITLE
Duration Debuff [Sunder Armor] condition not working.  

### ISSUE THREAD

**Issue by juggarrnaut** [ascott18/TellMeWhen#1800] opened 2020-08-03 18:59 UTC
**What version of TellMeWhen are you using? **
TellMewhen-8.75-classic

**What steps will reproduce the problem?**
1. /tmw
2. create new spell cooldown
3. What to track: Sunder Armor
4. Select Conditions Tab
5. 
Debuff - Duration, target < 11 secs
Sunder Armor

**What do you expect to happen? What happens instead?**
The Icon displays when the debuff goes below 11 seconds

I reapply the debuff

What I expect to happen: 
I expect that after reapplying the debuff it will not show the icon again until the debuff goes below 11 seconds

What happens instead:
After I reapply the debuff the icon is shown no matter what the debuff duration, even when the duration is above 11 seconds.

**Screenshots and Export Strings**

**Additional Info**

**Comment by ascott18** [comment] 2020-08-26 02:22
Duplicate of #1792

**Closed by ascott18** 2020-08-26 02:22 UTC
