### ISSUE TITLE
[Bug]: TMW not loading with WoW startup

### ISSUE THREAD

**Issue by CaRuJa1** [ascott18/TellMeWhen#1980] opened 2022-10-28 09:22 UTC
### WoW Version

Retail

### TellMeWhen Version

v10.0.0 r1 (g6f25cd2)

### Describe the bug

Apologies in advance for the poor formatting.

62x TellMeWhen: ...en/Components/IconModules/IconModule_Texts/Texts.lua:696: bad argument #1 to 'SetEndDelay' (must be a finite number - Usage: self:SetEndDelay(delaySec [, recomputeGroupDuration]))
[string "@Interface/AddOns/TellMeWhen/TellMeWhen.lua"]:2875: in function <Interface/AddOns/TellMeWhen/TellMeWhen.lua:2832>

Since dragonflight launched I have an issue where TMW either doesnt launch my profile (or possibly just stays invisible) when I log in to the game or /reload, and shows the BugSack string above. If I enter a /tmw command it force loads it, and then allows me to continue as normal.  For some reason it only effects one spec of one character, and all other specs and characters are fine.

The string below in the link is what BugSack shows after force loading:

https://pastebin.com/tpNb7Z9v

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment] 2022-10-29 02:26
Duplicate of #1977

**Closed by ascott18** 2022-10-29 02:26 UTC
