### ISSUE TITLE
attempt to call upvalue 'OnGCD' (a nil value)

### ISSUE THREAD

**Issue by StanoRiga** [ascott18/TellMeWhen#2218] opened 2024-09-05 08:48 UTC
### WoW Version

Retail

### TellMeWhen Version

11.0.6

### Describe the bug

The following error occurs and is constantly counting up so Blizz is constantly reporting too many UI errors.
After clicking "Zweckentfremdeter Teufelsfokussierer" (Repurposed Fel Focuser, https://www.wowhead.com/item=147707).
This did not happen yesterday before the app update.
The error counting stops when TMW is in edit mode, and continues as soon as edit mode is left.
The same behavior is for "Traumgebundene Verstärkungsrune" (Dreambound Augment Rune, https://www.wowhead.com/item=211495)

3277x ...ceTellMeWhen/Components/Core/Common/Item.lua:168: attempt to call upvalue 'OnGCD' (a nil value)
[string "@TellMeWhen/Components/Core/Common/Item.lua"]:168: in function `GetCooldownDurationNoGCD'
[string "Condition_BUFFDUR_ITEMCD_BUFFDUR"]:4: in function `CheckFunction'
[string "@TellMeWhen/Components/Core/Conditions/ConditionObject.lua"]:266: in function `Check'
[string "@TellMeWhen/Components/Core/Icon.lua"]:770: in function <TellMeWhen/Components/Core/Icon.lua:741>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@TellMeWhen/TellMeWhen.lua"]:2647: in function <TellMeWhen/TellMeWhen.lua:2609>

Locals:
self = <table> {
 name = "traumgebundene verstärkungsrune"
 what = "traumgebundene verstärkungsrune"
}
start = 1903585.050000
duration = 60
enable = true
(*temporary) = nil
(*temporary) = 60
(*temporary) = "attempt to call upvalue 'OnGCD' (a nil value)"
OnGCD = nil
TMW = TMW {
 modules = <table> {
 }
 GroupsToUpdate = <table> {
 }
 GCDSpell = 53
 Classes = <table> {
 }
 DS = <table> {
 }
 Warned = true
 isRetail = true
 Initialized = true
 EquivFirstIDLookup = <table> {
 }
 Group_Defaults = <table> {
 }
 EquivFullNameLookup = <table> {
 }
 SpellTexturesMetaIndex = <table> {
 }
 DEFAULT_ICON_SETTINGS = <table> {
 }
 HaveUpgradedOnce = true
 db = <table> {
 }
 InitializedDatabase = true
 BE = <table> {
 }
 TIMERS = <table> {
 }
 CovenantIcons = <table> {
 }
 COUNTERS = <table> {
 }
 COMMON = <table> {
 }
 IconEventUpdateEngine = Frame {
 }
 TEXT = <table> {
 }
 CNDT = <table> {
 }
 performedEvent = "TMW_UPGRADE_PERFORMED"
 UNITS = <table> {
 }
 EquivFullIDLookup = <table> {
 }
 profile = <table> {
 }
 name = "TellMeWhen"
 CompareFuncs = <table> {
 }
 DOGTAG = <table> {
 }
 Defaults = <table> {
 }
 C = <table> {
 }
 IconStateArbitrator = <table> {
 }
 time = 1903585.282000
 SNIPPETS = <table> {
 }
 L = <table> {
 }
 OrderedTypes = <table> {
 }
 Views = <table> {
 }
 isCata = false
 baseName = "TellMeWhen"
 defaultModuleState = true
 OrderedViews = <table> {
 }
 strlowerCache = <table> {
 }
 UPD_INTV = 0.051000
 isWrath = false
 Locked = true
 NAMES = <table> {
 }
 GUIDToOwner = <table> {
 }
 spellTextureCache = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 global = <table> {
 }
 IconsToUpdate = <table> {
 }
 isClassic = false
 EventList = <table> {
 }
 ValidityCheckQueue = <table> {
 }
 orderedModules = <table> {
 }
 EVENTS = <table> {
 }
 EquivOriginalLookup = <table> {
 }
 Types = <table> {
 }
 enabledState = true
 isNumber = <table> {
 }
 PreviousGUIDToOwner = <table> {
 }
 callbackregistry = <table> {
 }
 CONST = <table> {
 }
 Icon_Defaults = <table> {
 }
}

### Export Strings

```text
^1^T^SType^Sbuff ^SName^STeufelsfokus ^SConditions^T ^N1^T ^SType^SBUFFDUR ^SName^SGroßes~`Fläschchen~`der~`unendlichen~`Tiefe ^t^N2^T ^SType^SBUFFDUR ^SName^SVerschleierte~`Verstärkung ^t^N3^T ^SType^SITEMCD ^SName^SZweckentfremdeter~`Teufelsfokussierer ^t^N4^T ^SType^SBUFFDUR ^SName^SIntelligenz ^t^N5^T ^SType^SBUFFDUR ^SName^SSpektralfläschchen~`der~`Macht ^t^N6^T ^SType^SBUFFDUR ^SName^SPhiole~`des~`elementaren~`Chaos ^t^Sn^N6 ^t^SCustomTex^S242551 ^SStates^T ^N1^T ^SAlpha^N0 ^t^N2^T ^SAlpha^N1 ^t^t^SEnabled^B ^t^N110601^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment] 2024-09-05 14:56
Duplicate of #2217

**Closed** 2024-09-05 14:56 UTC
