### ISSUE TITLE
When Range Check or Power Check Used, Spell Cooldowns Show Before Cooldown is Available

### ISSUE THREAD

**Issue by StreetLight777** [ascott18/TellMeWhen#2117] opened 2023-11-13 23:54 UTC
### WoW Version

Retail

### TellMeWhen Version

10.1.6

### Describe the bug

If I set a 'Power Check' or 'Range Check' condition on a spell cooldown, TellMeWhen will show the icon in many (all?) cases before the spell cooldown is actually up if I'm out of range or out of energy - it's as if the spell cooldown condition isn't being evaluated first in the list. It's been like this for years, but I never thought to report it before now. It's pretty annoying - to the point where I can't use range or power checks.

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment] 2023-11-18 04:28
Duplicate of #2116

**Closed by ascott18** 2023-11-18 04:28 UTC

**Comment by StreetLight777** [comment] 2023-11-18 07:09
“I'm afraid I really don't understand why you'd want to check for
power/range when a spell is *on* cooldown while also *not* wanting to see
that information when the spell is *off* cooldown. Suppose its off cooldown
and out of range - what's the point in not being able to see that?

I also don't quite understand the desire to have an icon show only when
something is unusable, and not show when usable, but that part does indeed
work. When a spell is out of range or out of power, it is unusable, and
that takes priority.”

It’s pretty simple really. The cooldown is the most constraining factor. I
can fix range or resources quickly, but I can’t make the cooldown tick
faster. So people want to know when a button is unusable (e.g. because out
of range or resource), but the cooldown is available. I can step forward a
few times and presto!

But if the icon shows as out of range, but the cooldown is not available,
what the point in that? Even if I get in range, I still can’t use the
button for 90 seconds… for example.

-- Keifer
