### ISSUE TITLE
[Bug] Evoker Eternity surge not tracking CD

### ISSUE THREAD

**Issue by Norvelas** [ascott18/TellMeWhen#2084] opened 2023-05-11 15:00 UTC
### WoW Version

Retail

### TellMeWhen Version

10.1.0

### Describe the bug

Evoker Eternity surge not tracking CD when being used. I've tried all the options that show up and even tried using their spell ID's respectively. Just doesn't track the CD

### Export Strings

```text
^1^T^SType^Scooldown ^SName^SEternity~`Surge ^SEnabled^B ^t^N101000^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment] 2023-05-12 20:48
Duplicate of #2081

**Closed by ascott18** 2023-05-12 20:48 UTC
