### ISSUE TITLE
[Bug]: Execute does not count for cooldown

### ISSUE THREAD

**Issue by smittan** [ascott18/TellMeWhen#2015] opened 2022-11-22 17:39 UTC
### WoW Version

Retail

### TellMeWhen Version

10.0.2

### Describe the bug

When the talent Massacre is taken, checks against cooldown doesn't work. Execute will always be ready as long as the target's health are below 35%. I do not have this issue when not using the Massacre talent and the target's health are below 20%.

![execute](https://user-images.githubusercontent.com/118843402/203382995-f29eb2a9-56ce-4a76-8e75-64e434362a9d.jpg)

### Export Strings

```text
^1^T^SShowTimer^B ^SType^Sreactive ^SName^SExecute ^SClockGCD^B ^SGUID^STMW:icon:1ZVGHiCnZr06 ^SCooldownCheck^B ^SStates^T ^N4^T ^SAlpha^N0 ^t^t^SRangeCheck^B ^SFakeHidden^B ^SEnabled^B ^t^N100200^S~`~| ^Sicon^^
```

**Comment by smittan** [comment] 2022-11-22 19:53
Apparently works using spellid 280735 (fury specific) instead of just typing in Execute. Cudos to Zanth discovering this!

**Comment by ascott18** [comment] 2022-11-22 21:56
Execute has been giga broken in wow's api for a while now. Duplicate of #1653

**Closed by ascott18** 2022-11-22 21:56 UTC
