### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by dvdio** [ascott18/TellMeWhen#1881] opened 2021-03-25 15:26 UTC
**What version of TellMeWhen are you using? **
9.0.5 and 9.0.6

**What steps will reproduce the problem?**
Not sure, sometimes when i pass mouse over the enemy frames i think, its usually in combat.
It happens multiple times, usually the lua is almost the same, i will paste 3 of them.

**What do you expect to happen? What happens instead?**
nothing except the lua error, everything seems to work

**Screenshots and Export Strings**
1 ----------------------------------------
Message: invalid key to 'next'
Time: Tue Mar 23 10:12:03 2021
Count: 1
Stack: invalid key to 'next'
[string "=[C]"]: in function `(for generator)'
[string "@Interface\AddOns\TellMeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua"]:59: in function <...MeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua:56>
[string "@Interface\AddOns\TellMeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua"]:66: in function <...MeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua:65>

Locals: (*temporary) = <table> {
}
(*temporary) = "raid1target"

2 ---------------------------------------------
Message: invalid key to 'next'
Time: Wed Mar 24 13:31:47 2021
Count: 6
Stack: invalid key to 'next'
[string "=[C]"]: in function `(for generator)'
[string "@Interface\AddOns\TellMeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua"]:59: in function <...MeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua:56>
[string "@Interface\AddOns\TellMeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua"]:66: in function <...MeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua:65>

Locals: (*temporary) = <table> {
 raid3target = true
}
(*temporary) = "raid10target"

3 ----------------------------------------
Message: invalid key to 'next'
Time: Thu Mar 25 15:23:44 2021
Count: 2
Stack: invalid key to 'next'
[string "=[C]"]: in function `(for generator)'
[string "@Interface\AddOns\TellMeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua"]:59: in function <...MeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua:56>
[string "@Interface\AddOns\TellMeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua"]:66: in function <...MeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua:65>

Locals: (*temporary) = <table> {
}
(*temporary) = "raid13target"

**Additional Info**
Sometimes it happens in arena as well, and there is no "raidXtarget" at the end

**Comment by ascott18** [comment] 2021-03-25 15:45
Dupe of #1879

**Closed by ascott18** 2021-03-25 15:45 UTC
