### ISSUE TITLE
[Bug] IceHUD

### ISSUE THREAD

**Issue by SpoofAccount** [ascott18/TellMeWhen#1891] opened 2021-04-26 01:50 UTC
**What version of TellMeWhen are you using? **

**What steps will reproduce the problem?**
1.
2.
3.

**What do you expect to happen? What happens instead?**

Hello.  Upon updating my game today TellMeWhen was non-functional, as well as the addon IceHUD.  I tried everything under the sun and moon and nothing worked.  I had to roll back TellMeWhen to its previous version and everything is fine again.  Previous versions of IceHUD would not work.  Other addons were also seemingly minorly interfered with.

Love the addon, i'm not sure who you are but i'm really thankful for all the work you put into this :)   

Made an account just to report this to give back and spread the knowledge. thanks.

**Screenshots and Export Strings**

**Additional Info**

**Comment by SpoofAccount** [comment] 2021-04-26 01:51
sorry, but updating my game i mean updating "TellMeWhen" to the April 24 version

**Comment by ascott18** [comment] 2021-04-26 05:14
This is caused by https://github.com/parnic/LibDogTag-3.0/issues/5. Until a new version of TMW is released, you can work around it by installing LibDogTag-3.0 90000.6 as a standalone addon (https://www.wowace.com/projects/libdogtag-3-0).

**Comment by ascott18** [comment] 2021-05-01 17:24
This can also be fixed by updating to the latest version of IceHUD

**Closed by ascott18** 2021-05-01 17:24 UTC
